import { initDemo1 } from './demo1';
import { initDemo1b } from './demo1b';
import { initDemo2 } from './demo2';
import { initDemo3 } from './demo3';
import { initDemo5 } from './demo5';
import { initDemo6 } from './demo6';
import { initDemo7 } from './demo7';
import { initDemo8 } from './demo8';
import { initDemo9 } from './demo9';
import { initDemo10 } from './demo10';

initDemo1();
initDemo1b();
initDemo2();
initDemo3();
initDemo5();
initDemo6();
initDemo7();
initDemo8();
initDemo9();
initDemo10();
